# SPDX-FileCopyrightText: Copyright © contributors to CNPG Extensions.
# SPDX-License-Identifier: Apache-2.0

ARG BASE=ghcr.io/cloudnative-pg/postgresql:18-minimal-trixie
FROM ${BASE} AS builder

ARG PG_MAJOR
ARG EXT_VERSION

USER 0

WORKDIR /build
ADD https://github.com/neondatabase/pg_session_jwt/archive/${EXT_VERSION}.tar.gz /tmp/source.tar.gz
RUN tar -xzf /tmp/source.tar.gz --strip-components=1 -C /build

COPY pg-session-jwt/patches/Cargo.lock.patch /build/Cargo.lock.patch
RUN if [ "${EXT_VERSION}" = "v0.5.0" ]; then \
      apt-get update && \
      apt-get install -y --no-install-recommends patch && \
      patch --batch --forward --strip=1 < /build/Cargo.lock.patch; \
    fi

COPY pgrx/ /pgrx/
RUN /pgrx/install-pgrx-build-environment.sh "${PG_MAJOR}" /build/Cargo.lock

# The upstream build example in Issue #28 uses `cargo pgrx install --release`:
# https://github.com/neondatabase/pg_session_jwt/issues/28#issuecomment-2685604932
# https://github.com/neondatabase/neon/blob/fa504217c61bbcaf5c512d75830564541f917f8f/compute/compute-node.Dockerfile#L1380
RUN cargo pgrx install --release

FROM scratch AS pgrx-sbom
COPY --from=builder /build/pgrx-sbom/ /pgrx-sbom/

FROM scratch
ARG PG_MAJOR

# Licenses
COPY --from=builder /build/pgrx-licenses/rust/ /licenses/rust/

# Libraries
COPY --from=builder /usr/lib/postgresql/${PG_MAJOR}/lib/pg_session_jwt.so /lib/

# Share
COPY --from=builder /usr/share/postgresql/${PG_MAJOR}/extension/pg_session_jwt* /share/extension/

USER 65532:65532
